### ISSUE TITLE
Status bar should be black

### ISSUE THREAD

**Issue by HappySmilyGuy** [HappySmilyGuy/iCU#3]

**Comment by peneycad118** [comment]
Hi Eddie have you fixed this with your latest changes?  I did something similar locally

**Comment by HappySmilyGuy** [comment]
I have not done it, I've only submitted the issue. Do submit a branch of the fix if you've managed it! :)

On Sun, Oct 30, 2016 at 12:44pm, peneycad118 < notifications@github.com [notifications@github.com] > wrote:
Hi Eddie have you fixed this with your latest changes? I did something similar locally

**Comment by peneycad118** [comment]
I have fixed this now - http://stackoverflow.com/questions/36095804/android-studio-white-bar-across-top
